"""One native OpenEnv session owns one independent live airline environment."""

from copy import deepcopy
from typing import Any

from openenv.core.env_server import Environment
from openenv.core.env_server.types import EnvironmentMetadata

from airline_recovery.live.environment import LiveAirlineEnv
from airline_recovery.live.evaluate import EASY_MAX_STEPS
from airline_recovery import __version__

from .models import AirlineAction, AirlineObservation, AirlineState, ResetOptions, SeedValue


class AirlineEnvironment(Environment[AirlineAction, AirlineObservation, AirlineState]):
    SUPPORTS_CONCURRENT_SESSIONS = True

    def __init__(self, max_steps: int | None = None):
        super().__init__()
        # LiveAirlineEnv starts workers on reset, not on construction. Discovery
        # endpoints can construct and close this object without starting a stack.
        # ``max_steps=None`` means 48 on the easy tier and the case's budget on the hard tier.
        self._max_steps = max_steps
        self._core_steps = EASY_MAX_STEPS if max_steps is None else max_steps
        self._core = LiveAirlineEnv(max_steps=self._core_steps, backend="sqlite")
        self._closed = False

    def _core_for(self, tier: str) -> LiveAirlineEnv:
        """A core sized for the tier: the budget is fixed at construction, so rebuild when it changes."""
        wanted = self._max_steps if self._max_steps is not None else (EASY_MAX_STEPS if tier == "easy" else None)
        if wanted != self._core_steps:
            self._core.close()
            self._core = LiveAirlineEnv(max_steps=wanted, backend="sqlite")
            self._core_steps = wanted
        return self._core

    def reset(
        self,
        seed: int | None = None,
        episode_id: str | None = None,
        split: str | None = None,
        index: int | None = None,
        tier: str | None = None,
        options: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> AirlineObservation:
        if self._closed:
            raise RuntimeError("This session has been closed. Open a new client session.")
        if kwargs:
            raise ValueError(f"Unknown reset parameters: {', '.join(sorted(kwargs))}")
        if episode_id is not None:
            raise ValueError("Episode IDs are generated by the environment; omit episode_id.")
        chosen = dict(options or {})
        if split is not None:
            chosen["split"] = split
        if index is not None:
            chosen["index"] = index
        if tier is not None:
            chosen["tier"] = tier
        validated = ResetOptions.model_validate(chosen)
        validated_seed = SeedValue(seed=0 if seed is None else seed).seed
        observation, info = self._core_for(validated.tier).reset(
            seed=validated_seed, options=validated.core_options()
        )
        return AirlineObservation(**observation, reward=0.0, done=False, metadata=info)

    def step(
        self,
        action: AirlineAction,
        timeout_s: float | None = None,
        **kwargs: Any,
    ) -> AirlineObservation:
        if self._closed:
            raise RuntimeError("This session has been closed. Open a new client session.")
        observation, reward, terminated, truncated, info = self._core.step(
            action.model_dump(exclude={"metadata"})
        )
        return AirlineObservation(
            **observation, reward=float(reward), done=bool(terminated or truncated),
            terminated=terminated, truncated=truncated, metadata=info,
        )

    @property
    def state(self) -> AirlineState:
        state = self._core.state()
        return AirlineState(
            episode_id=state.get("episode_id"),
            step_count=state.get("step_count", 0),
            done=state.get("done", False),
        )

    def close(self) -> None:
        if not self._closed:
            self._core.close()
            self._closed = True

    def list_splits(self) -> list[str]:
        return list(self._core.task_manifest())

    def list_tasks(self, split: str, tier: str = "easy") -> list[dict[str, Any]]:
        manifest = self._core.task_manifest(tier) if tier != "easy" else self._core.task_manifest()
        if split not in manifest:
            # Native Task API maps IndexError to a HTTP 400 response.
            raise IndexError(f"Unknown split: {split}")
        return deepcopy(manifest[split])

    def num_tasks(self, split: str, tier: str = "easy") -> int:
        return len(self.list_tasks(split, tier))

    def get_task(self, split: str, index: int, tier: str = "easy") -> dict[str, Any]:
        tasks = self.list_tasks(split, tier)
        if index < 0 or index >= len(tasks):
            raise IndexError("Task index is out of range")
        return tasks[index]

    def get_task_range(
        self, split: str, start: int | None = None, stop: int | None = None
    ) -> list[dict[str, Any]]:
        return self.list_tasks(split)[start:stop]

    def get_metadata(self) -> EnvironmentMetadata:
        return EnvironmentMetadata(
            name="airline_recovery", version=__version__,
            description=(
                "Diagnose and repair booking-to-checkin incidents in five local HTTP "
                "services. Rewards come from executed transactions and database integrity."
            ),
            readme_content=(
                "# Airline Recovery Env\n\n"
                "Reset a task, inspect metrics/logs/configuration, apply a repair, "
                "probe transactions, then finish for an independent score. "
                "The initial observation lists tool schemas. Example action: "
                '`{"tool":"get_metrics","arguments":{}}`. '
                "Reset with `tier=\"hard\"` for the generated hard tier, whose budget "
                "comes from the case.\n\n"
                "Five HTTP worker processes and an isolated SQLite WAL database run "
                "per episode. This is synthetic application behavior, not a production "
                "airline, Kubernetes cluster or Kafka deployment. "
                "The web playground is a shared local debugging session; training "
                "clients use independent /ws sessions."
            ),
        )
